---
services:
  garmin-ign-bdtopo-map:
    container_name: garmin-ign-bdtopo-map
    build: .
    restart: unless-stopped
    ports:
      - 8088:8000
    volumes:
      - ./:/docs
    environment:
      TZ:  Europe/Paris
    networks:
      - garmin-ign-bdtopo-map

networks:
  garmin-ign-bdtopo-map:
    name: garmin-ign-bdtopo-map
    driver: bridge
    ipam:
      config:
        - subnet: "172.24.0.0/16"
          gateway: "172.24.0.1"